<?php
/**
 * @Created by PhpStorm.
 * @Project: XtCms
 * @User: Coopoo
 * @Copy Right: 2014
 * @Date: 2014-07-28
 * @Time: 14:20
 * @QQ: 259522
 * @FileName: list.phtml
 */
$this->headTitle('角色列表');
?>
<div class="table-responsive">
    <table class="table table-hover table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>角色名称</th>
        <th>角色状态</th>
        <th>编辑时间</th>
        <th>编辑IP</th>
        <th>管理</th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($roles) > 0): ?>
        <?php foreach ($roles as $role): ?>
            <tr>
                <td><?= $role->getId() ?></td>
                <td><?= $role->getName() ?></td>
                <td><?= $this->Status($role->getStatus(), 'Xt_Role/default', ['id' => $role->getId()]) ?></td>
                <td><?= $role->getModifyTime() ?></td>
                <td><?= $role->getModifyIp() ?></td>
                <td>
                    <a href="<?php echo $this->url('Xt_Role/default', ['action' => 'edit', 'id' => $role->getId()]) ?>"
                       class="btn btn-default">编辑</a>
                    <a href="<?php echo $this->url('Xt_Role/default', ['action' => 'delete', 'id' => $role->getId()]) ?>"
                       class="btn btn-primary"
                       onclick="JavaScript:return confirm('警告: 确定要删除角色 <?= $role->getName() ?> ?该操作不可还原!')">删除</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="6">
                没有数据
            </td>
        </tr>
    <?php endif ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="6">
            <?= $this->paginationControl($roles) ?>
        </td>
    </tr>
    </tfoot>
</table>
</div>