<?php
/**
 * @Created by PhpStorm.
 * @Project: XtCms
 * @User: Coopoo
 * @Copy Right: 2014
 * @Date: 2014-07-28
 * @Time: 14:20
 * @QQ: 259522
 * @FileName: list.phtml
 */
$this->headTitle('角色列表');
?>
<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>角色名称</th>
        <th>角色状态</th>
        <th>编辑时间</th>
        <th>编辑IP</th>
        <th>管理</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($roles as $role): ?>
        <tr>
            <td><?= $role->getId() ?></td>
            <td><?= $role->getName() ?></td>
            <td>
                <?php if ($role->getStatus() === 99): ?>
                    <a class="btn btn-primary">正常</a> <a
                        href="<?php echo $this->url('Xt_Role/default', ['action' => 'disabled', 'id' => $role->getId()]) ?>"
                        class="btn btn-default">点击禁用</a>
                <?php else: ?>
                    <a class="btn btn-primary">禁用</a> <a
                        href="<?php echo $this->url('Xt_Role/default', ['action' => 'enabled', 'id' => $role->getId()]) ?>"
                        class="btn btn-default">点击启用</a>
                <?php endif; ?>
            </td>
            <td><?= $role->getModifyTime() ?></td>
            <td><?= $role->getModifyIp() ?></td>
            <td>
                <a href="<?php echo $this->url('Xt_Role/default', ['action' => 'edit', 'id' => $role->getId()]) ?>"
                   class="btn btn-default">编辑</a>
                <a href="<?php echo $this->url('Xt_Role/default', ['action' => 'delete', 'id' => $role->getId()]) ?>"
                   class="btn btn-primary"
                   onclick="JavaScript:return confirm('警告: 确定要删除角色 <?= $role->getName() ?> ?该操作不可还原!')">删除</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="6">
            <?= $this->paginationControl($roles) ?>
        </td>
    </tr>
    </tfoot>
</table>
