<?php
/**
 * @Created by PhpStorm.
 * @Project: XtCms
 * @User: Coopoo
 * @Copy Right: 2014
 * @Date: 2014-07-28
 * @Time: 14:20
 * @QQ: 259522
 * @FileName: list.phtml
 */
$this->headTitle('资源列表');
?>
<div class="table-responsive">
    <table class="table table-hover table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>资源名称</th>
        <th>编辑时间</th>
        <th>编辑IP</th>
        <th>管理</th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($resources) > 0): ?>
    <?php foreach ($resources as $resource): ?>
        <tr>
            <td><?= $resource->getId() ?></td>
            <td><?= $resource->getName() ?></td>
            <td><?= $resource->getModifyTime() ?></td>
            <td><?= $resource->getModifyIp() ?></td>
            <td>
                <a href="<?php echo $this->url('Xt_Resource/default', ['action' => 'edit', 'id' => $resource->getId()]) ?>"
                   class="btn btn-default">编辑</a>
                <a href="<?php echo $this->url('Xt_Resource/default', ['action' => 'delete', 'id' => $resource->getId()]) ?>"
                   class="btn btn-primary"
                   onclick="JavaScript:return confirm('警告: 确定要删除资源 <?= $resource->getName() ?> ?该操作不可还原!')">删除</a>
            </td>
        </tr>
    <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="5">
                没有数据
            </td>
        </tr>
    <?php endif ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="5">
            <?= $this->paginationControl($resources) ?>
        </td>
    </tr>
    </tfoot>
</table>
</div>