<?php
/**
 * @Created by PhpStorm.
 * @Project: XtCms
 * @User: Coopoo
 * @Copy Right: 2014
 * @Date: 2014-07-28
 * @Time: 14:20
 * @QQ: 259522
 * @FileName: list.phtml
 */
$this->headTitle('角色列表');
?>
<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>角色名称</th>
        <th>角色状态</th>
        <th>编辑时间</th>
        <th>编辑IP</th>
        <th>管理</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($roles as $role): ?>
        <tr>
            <td><?= $role->getId() ?></td>
            <td><?= $role->getName() ?></td>
            <td><?= ($role->getStatus() === 1) ? '正常' : '禁用' ?></td>
            <td><?= $role->getModifyTime() ?></td>
            <td><?= $role->getModifyIp() ?></td>
            <td>
                <a href="<?php echo $this->url('Xt_Role/default', ['action' => 'edit', 'id' => $role->getId()]) ?>">编辑</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="6">
            <?= $this->paginationControl($roles, null, null, ['actionArray' => ['action' => 'list']]) ?>
        </td>
    </tr>
    </tfoot>
</table>

