<?php
/**
 * @Created by PhpStorm.
 * @Project: XtCms
 * @User: Coopoo
 * @Copy Right: 2014
 * @Date: 2014-07-28
 * @Time: 15:21
 * @QQ: 259522
 * @FileName: pagination.phtml
 */

if ($this->pageCount < 2) {
    return;
}
$routeMatch = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$action = $routeMatch->getParam('action');
?>
    <div class="paginationControl pull-right">
        <ul class="pagination">
            <!-- First page link -->
            <?php if (isset($this->previous)): ?>
                <li class=""><a
                        href="<?= $this->url($this->route, ['action' => $action, 'page' => $this->first]); ?>">
                        首页
                    </a></li>
            <?php else: ?>
                <li class="disabled"><span>首页</span></li>
            <?php endif; ?>

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class=""><a
                        href="<?= $this->url($this->route, ['action' => $action, 'page' => $this->previous]) ?>">
                        &laquo;上一页
                    </a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">&laquo;</a></li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li class=""><a
                            href="<?= $this->url($this->route, ['action' => $action, 'page' => $page]) ?>">
                            <?= $page; ?>
                        </a></li>
                <?php else: ?>
                    <li class="active"><a href="#"><?= $page ?><span class="sr-only">(current)</span></a></li>
                <?php endif; ?>
            <?php endforeach; ?>


            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li class=""><a
                        href="<?= $this->url($this->route, ['action' => $action, 'page' => $this->next]); ?>">
                        下一页 &raquo;
                    </a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">&raquo;</a></li>
            <?php endif; ?>
            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
                <li class=""><a
                        href="<?= $this->url($this->route, ['action' => $action, 'page' => $this->last]); ?>">
                        尾页
                    </a></li>
            <?php else: ?>
                <li class="disabled"><span>尾页</span></li>
            <?php endif; ?>
        </ul>
    </div>
