<?php
/**
 * @Created by PhpStorm.
 * @Project: XtCms
 * @User: Coopoo
 * @Copy Right: 2014
 * @Date: 2014-06-30
 * @Time: 12:42
 * @QQ: 259522
 * @FileName: index.phtml
 */
?>
<form method="post" action="<?= $this->url(null, ['action' => 'back']) ?>" name="dbBack" class="form-horizontal"
      role="form">
    <table class="table">
        <thead>
        <tr>
            <th>选择</th>
            <th>表名</th>
            <th>行数</th>
            <th>类型</th>
            <th>排序规则</th>
            <th>大小</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($dbState as $table): ?>
            <tr>
                <td><input type="checkbox" name="tables[]" value="<?= $table['Name'] ?>"/></td>
                <td><?= $table['Name'] ?></td>
                <td><?= $table['Rows'] ?></td>
                <td><?= $table['Engine'] ?></td>
                <td><?= $table['Collation'] ?></td>
                <td><?= round(($table['Data_length'] + $table['Index_length']) / 1024, 2) . ' KB' ?></td>
                <td>
                    <a href="<?= $this->url(null, ['action' => 'truncate', 'id' => $table['Name']]) ?>"
                       onclick="JavaScript:return confirm('警告: 确定要清空数据表 <?= $table['Name'] ?> ?该操作不可还原!')">清空</a>
                    <a href="<?= $this->url(null, ['action' => 'drop', 'id' => $table['Name']]) ?>"
                       onclick="JavaScript:return confirm('警告: 确定要删除数据表 <?= $table['Name'] ?> ?该操作不可还原!')">删除</a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="7">
                <input type="checkbox"> 全选/反选 <br>

                <div class="row">
                    <div class="form-group">
                        <label for="file_name" class="col-sm-2 control-label">文件名</label>

                        <div class="col-sm-8">
                            <input type="text" name="file_name" class="form-control" value="" placeholder="请输入备份文件名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="bak" class="col-sm-2 control-label">备份类型</label>

                        <div class="col-sm-8">
                            <label class="radio-inline">
                                <input type="radio" name="back_type" id="inlineRadio1" value="0" checked="checked">
                                结构和数据
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="back_type" id="inlineRadio2" value="1"> 只结构
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="back_type" id="inlineRadio3" value="2"> 只数据
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="bak" class="col-sm-2 control-label">备注信息</label>

                        <div class="col-sm-8">
                            <input type="text" name="bak" class="form-control" value="" placeholder="请输入备注信息">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-8">
                            <button type="submit" class="btn btn-default">批量备份</button>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        </tfoot>
    </table>
</form>

<table class="table">
    <thead>
    <tr>
        <th></th>
        <th>文件名</th>
        <th>备份时间</th>
        <th>备注</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($backFile as $key => $file):
        if ($key < 15):
            ?>
            <tr>
                <td></td>
                <td><?= $file['name'] ?></td>
                <td><?= $file['time'] ?></td>
                <td><?= $file['bak'] ?></td>
                <td>
                    <a href="<?= $this->url(null, ['action' => 'unlink', 'id' => $file['e_name']]) ?>"
                       onclick="JavaScript:return confirm('警告: 确定要删除 <?= $file['name'] ?> ?该操作不可还原!')">删除</a>
                    <a href="<?= $this->url(null, ['action' => 'restore', 'id' => $file['e_name']]) ?>"
                       onclick="JavaScript:return confirm('警告: 确定要还原 <?= $file['name'] ?> ?该操作不可还原!')">还原</a>
                </td>
            </tr>
        <?php
        endif;
    endforeach;
    ?>
    </tbody>
</table>